version: "3.5"

services:
  app:
    container_name: app
    image: gingonic/template:latest
    ports: 
      - ${RUN_PORT}:${RUN_PORT}
    networks: 
      - backend
    restart: unless-stopped
    env_file: .env-docker
    healthcheck:
      test: curl --location --request GET `http://localhost:${RUN_PORT}/billing/m/health_check` || exit 1z
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  backend:    